---
- hosts: localhost
  remote_user: root
  gather_facts: false

  tasks:
    - name: "datetime filter"
      debug: msg="{{ (("2016-08-04 20:00:12"|to_datetime) - ("2015-10-06"|to_datetime('%Y-%d-%m'))).seconds  }}"
