---
- hosts: localhost
  remote_user: root
  gather_facts: false

  vars:
    name: "John"

  tasks:

    - name: "true or false take different value"
      debug: msg="{{ (name == "John") | ternary('Mr','Ms') }}"