---
- hosts: localhost
  remote_user: root
  gather_facts: false

  vars:
    my_comment: "This is the test comment"
  tasks:
    - name: "Use multiple filter in chain"
      debug: msg="{{ [0,2] | map('extract', ['x','y','z']) | join('|') }}"
