---
- hosts: localhost
  remote_user: root
  gather_facts: false

  vars:
    domain_definition:
      domain:
          cluster:
              - name: "cluster1"
              - name: "cluster2"
          server:
              - name: "server11"
                cluster: "cluster1"
                port: "8080"
              - name: "server12"
                cluster: "cluster1"
                port: "8090"
              - name: "server21"
                cluster: "cluster2"
                port: "9080"
              - name: "server22"
                cluster: "cluster2"
                port: "9090"
          library:
              - name: "lib1"
                target: "cluster1"
              - name: "lib2"
                target: "cluster2"

  tasks:
    #Need to install extra python module by following:
    #sudo pip install jmespath
    - name: "Display all cluster names"
      debug: var=item
      with_items: "{{domain_definition|json_query('domain.cluster[*].name')}}"
    - name: "Display all server names"
      debug: var=item
      with_items: "{{domain_definition|json_query('domain.server[*].name')}}"
    - name: "Display all server names from cluster1"
      debug: var=item
      with_items: "{{domain_definition|json_query(server_name_cluster1_query)}}"
      vars:
        server_name_cluster1_query: "domain.server[?cluster=='cluster1'].port"
    - name: "Display all server ports and names from cluster1"
      debug: var=item
      with_items: "{{domain_definition|json_query(server_name_cluster1_query)}}"
      vars:
        server_name_cluster1_query: "domain.server[?cluster=='cluster2'].{name: name, port: port}"