---
- hosts: localhost
  remote_user: root
  gather_facts: false

  vars:
    some_string_value: "Test"
    some_book_value: True

  tasks:

    - debug: msg=test
      when: some_string_value | bool
    - debug: msg=test
      when: some_book_value | bool
