---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - debug: msg="{{ lookup('etcd', 'foo') }} is a value from a locally running etcd"
    # the result value is alway empty, can't get the reason
