---
- hosts: all
  remote_user: root

  tasks:
    - debug: msg="The atomic number of Lithium is {{ lookup('csvfile', 'Li file=data/elements.csv delimiter=,') }}"
    - debug: msg="The atomic mass of Lithium is {{ lookup('csvfile', 'Li file=data/elements.csv delimiter=, col=2') }}"
